### ISSUE TITLE
Using long data type in min_value and max_value

### ISSUE THREAD

**Issue by javaherisaber** [jemshit/crystal-range-seekbar#2]
how do i use `Long` data type in this library ?
setMinValue() and setMaxValue() both are taking float arguments !

**Comment by jemshit** [comment]
`longValue.toFLoat()` 🤷‍♂️

**Comment by javaherisaber** [comment]
@jemshit 
`longValue.toFLoat()` is okay to use for this case
but there is another critical problem
`setMinStartValue()` and `setMaxStartValue()` not working in code
i need to display already selected range to user
any idea ?

**Comment by javaherisaber** [comment]
@jemshit 
please update library to support setMinStartValue() and setMaxStartValue()

**Comment by jemshit** [comment]
Maybe:
```
slide_switch.setMinValue(minValue.toFloat())
slide_switch.setMinStartValue(selectedMinValue.toFloat())

slide_switch.setMaxValue(maxValue.toFloat())
slide_switch.setMaxStartValue(selectedMaxValue.toFloat())

slide_switch.apply()
```

**Comment by javaherisaber** [comment]
> slide_switch.setMinValue(minValue.toFloat())
> slide_switch.setMinStartValue(selectedMinValue.toFloat())
>
> slide_switch.setMaxValue(maxValue.toFloat())
> slide_switch.setMaxStartValue(selectedMaxValue.toFloat())
>
> slide_switch.apply()

this worked for me
Thank you
